
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package BackEnd;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int LIMIT = 16;
  public static final int PROMPT = 11;
  public static final int COLON = 9;
  public static final int KLEENE = 14;
  public static final int RW_CONJ = 2;
  public static final int SET = 3;
  public static final int CONCAT = 15;
  public static final int EOF = 0;
  public static final int VALUE = 5;
  public static final int POSITIVE = 13;
  public static final int RBRACKET = 7;
  public static final int ID = 4;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int SEMICOLON = 8;
  public static final int LBRACKET = 6;
  public static final int OR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_CONJ",
  "SET",
  "ID",
  "VALUE",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "PROMPT",
  "OR",
  "POSITIVE",
  "KLEENE",
  "CONCAT",
  "LIMIT"
  };
}

